### ISSUE TITLE
Hilt

### ISSUE THREAD

**Issue by AbdElraoufSabri** [phansier/Clean-multimodel-arch#4]
Will it be painful to use it throughout the project?

**Comment by phansier** [comment]
@AbdElraoufSabri Thanks for the question. 

Actually we did not find Hilt useful for our project as it seems to be yet another abstraction over Dagger 2. However, it brings additional code generation and impact on compile time.

I suppose Hilt can be used with such an approach as it is built over Dagger 2 and as the approach itself can be used with any Dependency Injection framework.
